### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by jolamar** [ITDCD/uits-web-boilerplate#9]
IUPUC is working on a modified version of our WCMS framework and they changed the naming convention from `containers > units > patterns` to `rows > columns > elements`. Their reasoning was it was something their contributors can relate to, such as using HTML tables or Excel. Thoughts on this?

**Comment by levimcg** [comment]
@jolamar The reason I chose `.containers` and `.units` was so that they would not conflict with Foundation and Bootstrap grid class names at the time, which I think it still might with Bootstrap. So, if people were loading those entire frameworks, and using our grid there wouldn't be a conflict. I don't think that really matters anymore, but I'm not overly concerned with the naming convention of the grid.

Also the system isn't based on individual unit that those frameworks call `.columns`, it's based on fractional chunks that occur most frequently 1/3 1/4 2/3 etc. At this point it would just be a lot of work going back and fixing stuff on our part without much pay-off. Does that make sense?

**Comment by jolamar** [comment]
Makes sense - no need to change it at this point. I don't think this will be an issue of understanding for the people who will be using this.
